- name: Dart and Flutter Package Publisher
  # You may pin to the exact commit or the version.
  # uses: k-paxian/dart-package-publisher@8ecb150dfe6de74abafe0faf3c208fe43f4af12a
  uses: k-paxian/dart-package-publisher@v1.3
  with:
    # (Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_ACCESS_TOKEN
    accessToken: 
    # (Required) Token from ~/.pub-cache/credentials.json. Use secrets.OAUTH_REFRESH_TOKEN
    refreshToken: 
    # (Optional) Overrides accessToken and refreshToken. Whole content of ~/.pub-cache/credentials.json. Use secrets.CREDENTIAL_JSON
    credentialJson: # optional
    # (Optional) Path to your package root in your repository
    relativePath: # optional, default is 
    # (Optional) Perform dry run only, no real publishing
    dryRunOnly: # optional
    # (Optional) Skip unit tests run
    skipTests: # optional
    # (Optional) Suppress using `build_runner` for unit tests run
    suppressBuildRunner: # optional
    # (Optional) Format code of project to get better score in pub.dev
    format: # optional
