name: Publish to pub.dev

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # tag pattern on pub.dev: '{{version}}'
      - "[0-9]+.[0-9]+.[0-9]+-*" # tag pattern on pub.dev: '{{version}}-{suffix}'

# Publish using custom workflow
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.4"
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force
